services:
  - type: web
    name: eventcrafter
    env: docker
    plan: free
    region: singapore
    branch: main
    repo: https://github.com/Dhruvkotak1/EventCrafter-deploy.git
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: gondola.proxy.rlwy.net
      - key: DB_PORT
        value: 15206
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: bgPOnluoJNHSdtyulxROPZpqXcVlsbaW
